### ISSUE TITLE
Support VS 2019?

### ISSUE THREAD

**Issue by ghost** [stevemk14ebr/CompileTime-String-Encryption#1]
Hello.

Support VS 2019?

Have nice day. Thanks.

**Comment by stevemk14ebr** [comment]
It should already be compatible with it, please try and let me know if i'm wrong. Let me explain:

Take a look at c1xx.dll located at (for me): C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64 . This is called by the compiler to actually read the source code files in, to do this they use _wsopen_s API. If we look at the imports of that dll we see that it's imported from 'api-ms-win-crt-stdio-l1-1-0.dll':

![c1xx.dll imports](https://i.imgur.com/0gAE9w6.png)

Now if you look at this projects source code you will see that i attempt to grab the handle to that 'api-ms-win-crt-stdio-l1-1-0.dll' here: 

https://github.com/stevemk14ebr/CompileTime-String-Encryption/blob/d761acc53441955bd5a04b841fefd1059bbe89d8/CTXorDLL/CTXorDLL.cpp#L136

and then hook the _wsopen_s API inside of it here: 
https://github.com/stevemk14ebr/CompileTime-String-Encryption/blob/d761acc53441955bd5a04b841fefd1059bbe89d8/CTXorDLL/CTXorDLL.cpp#L155

**Comment by ghost** [comment]
I think not working.

![2019-06-05 06_23_54-TestXor - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/8020186/58928286-8930e480-875a-11e9-8026-eb36b2ce87ca.png)


Search 
![2019-06-05 06_25_35-TestXor - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/8020186/58928341-cb5a2600-875a-11e9-8ab9-6c50ada3cbdf.png)

**Comment by ghost** [comment]
Hmm. `testxor_crypt.cpp` contains main.cpp code. It is okay?

![2019-06-05 06_31_18-Window](https://user-images.githubusercontent.com/8020186/58928561-9e5a4300-875b-11e9-86b7-7281145bc422.png)

**Comment by stevemk14ebr** [comment]
Yes the hook is at least working. If you look in the visual studio console at the bottom you will see output such as 'Encrypting:'. So it intercepted you source file on the way to the compiler, and tried to encrypt, making a new copy called testxor_crypt.cpp

However you are using the macro wrong. You must put the string literal itself in the macro: ENC("hello world"). It's not smart enough to handle std::string, assign to a standard string after encryption

**Comment by ghost** [comment]
@stevemk14ebr Yes. Worked.

You can make an extended version of the project with https://github.com/JustasMasiulis/xorstr ?

**Comment by stevemk14ebr** [comment]
Yea probably, feel free to submit a PR to this project with improvements. This is a toy to me and I won't be doing anymore work on it
