### ISSUE TITLE
pch.h include error

### ISSUE THREAD

**Issue by ghost** [stevemk14ebr/CompileTime-String-Encryption#2]
Created `pch_crypt.cpp` empty file.

![2019-06-05 08_55_58-khaleesi - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/8020186/58933396-c489de00-876f-11e9-8cd2-65cbdb265bb8.png)

**Comment by stevemk14ebr** [comment]
I don't use pch files, I don't know and won't support
